/**
 * THIS FILE IS AUTO-GENERATED - DO NOT EDIT DIRECTLY
 * -----------------------------------------------
 * Generated by the DI generator script.
 *
 * To add new injectable classes, use the @injectable decorator from src/platform/common/di/injectable.ts
 * Example: @injectable('MyServiceId', 'Singleton')
 *
 * Run 'npm run generate-di' to regenerate this file after adding new injectable classes.
 */
import { Container } from 'inversify';
import getContainer, { registerModule } from '../core/di/registry';

let container: Container;
const provider = {
  async get<T>(id: string): Promise<T> {
    if (!container) {
      // Configure container based on environment
      // Create an array to hold all modules
      const modules: any[] = [];

      // Add environment-specific modules
      if (typeof window === 'undefined') {
        // Server-side modules
        modules.push(
          await import('./emporix/config/impl/EmporixConfigServer'),
          await import('./emporix/common/impl/EmporixTokenManagerServer'),
        );
      } else {
        // Client-side modules
        modules.push(
          await import('./emporix/config/impl/EmporixConfigClient'),
          await import('./emporix/common/impl/EmporixTokenManagerClient'),
        );
      }

      // Add common modules for both client and server
      modules.push(
        await import('./emporix/product/impl/EmporixProductApi'),
        await import('./emporix/catalog/impl/EmporixCatalogApi'),
        await import('./emporix/oauth/impl/EmporixOAuthApi'),
        await import('./emporix/common/impl/EmporixApiInvoker'),
        await import('./emporix/ai/impl/EmporixAIApi'),
      );

      // Register all modules
      for (const m of modules) {
        registerModule(m, 'integration');
      }
      // Initialize container
      container = await getContainer('integration');
    }
    return container.get<T>(id);
  },
};
export default provider;
