/**
 * Type-safe i18n message keys for next-intl.
 *
 * This augments `next-intl`'s `AppConfig` so that:
 * - `useTranslations('badNamespace')` shows a TypeScript error in the IDE
 * - `t('badKey')` shows a TypeScript error in the IDE
 * - Autocomplete works for namespaces and keys
 *
 * The combined `en.json` is auto-generated by `next-intl-split` when you
 * run `npm run dev` or `npm run build`. On a fresh clone you must run one
 * of those commands first so that the type information is available.
 */
import { routing } from './routing';
import en from './translations/en.json';

type Messages = typeof en;

declare module 'next-intl' {
  interface AppConfig {
    Locale: (typeof routing.locales)[number];
    Messages: Messages;
  }
}
