import type { AbstractIntlMessages } from 'next-intl';
import { hasLocale } from 'next-intl';
import { loadI18nTranslations } from 'next-intl-split/load';
import { getRequestConfig } from 'next-intl/server';
import { routing } from './routing';

export default getRequestConfig(async ({ requestLocale }) => {
  // Typically corresponds to the `[locale]` segment
  const requested = await requestLocale;
  const locale = hasLocale(routing.locales, requested) ? requested : routing.defaultLocale;

  let messages: AbstractIntlMessages;
  if (process.env.NODE_ENV === 'development') {
    // The provided route should starts from the src folder with the Relative approach.
    //
    // NOTE: Do NOT pass the 3rd `enableTypeCheck` arg (`true`) here. That flag makes
    // next-intl-split `writeFileSync` the merged `src/i18n/translations/<locale>.json`
    // files on EVERY request. Because those files live inside the Next dev-watched `src`
    // tree, each write triggers Fast Refresh, which issues an RSC refetch
    // (`next-hmr-refresh: 1`), which re-runs this config and rewrites the files again —
    // an infinite HMR loop that floods the network tab. The merged `<locale>.json` files
    // (used for TS message types) are generated by the next-intl-split plugin at build time.
    messages = loadI18nTranslations('./src/i18n/translations', locale);
  } else {
    // The relative path to the dictionaries folder
    messages = (await import(`./translations/${locale}.json`)).default;
  }

  return {
    locale,
    messages,
  };
});
