/**
 * THIS FILE IS AUTO-GENERATED - DO NOT EDIT DIRECTLY
 * -----------------------------------------------
 * Generated by the DI generator script.
 *
 * To add new injectable classes, use the @injectable decorator from src/platform/common/di/injectable.ts
 * Example: @injectable('MyServiceId', 'Singleton')
 *
 * Run 'npm run generate-di' to regenerate this file after adding new injectable classes.
 */
import type { Container } from 'inversify';
import getContainer, { registerModule } from '../core/di/registry';

let container: Container;
const provider = {
  async get<T>(id: string): Promise<T> {
    if (!container) {
      // Configure container based on environment
      // Create an array to hold all modules
      const modules: any[] = [];

      // Add environment-specific modules
      if (typeof window === 'undefined') {
        // Server-side modules
        modules
          .push
          // No server-side modules to register
          ();
      } else {
        // Client-side modules
        modules
          .push
          // No client-side modules to register
          ();
      }

      // Add common modules for both client and server
      modules
        .push
        // No common modules to register
        ();

      // Register all modules
      for (const m of modules) {
        registerModule(m, 'repository');
      }
      // Initialize container
      container = await getContainer('repository');
    }
    return container.get<T>(id);
  },
};
export default provider;
