import { inject } from 'inversify';
import { injectable } from '@/platform/core/di/injectable';
import type { EmporixSchemaApi } from '@/platform/integrations/emporix/schema/EmporixSchemaApi';
import type { LoggerService } from '@/platform/services/logger/LoggerService';
import { buildThemeEntityId } from '../../lib/cms-theme';
import { parseVersionedId } from '../../lib/version-utils';
import type { EmporixCmsThemeApi as IEmporixCmsThemeApi, RawCmsTheme } from '../EmporixCmsThemeApi';

/**
 * Emporix Custom Entities-backed implementation of the Theme API.
 *
 * Mirrors the shape of `EmporixCmsApi` so operational behaviour (direct
 * id lookup, fallback search, defensive JSON parsing) is consistent
 * across CMS entities.
 */
/**
 * TTL applied to the underlying Emporix reads (seconds).
 *
 * The fetch invoker translates this into `cache: 'force-cache'` +
 * `next: { revalidate }`, which is Next's data-cache equivalent of the
 * old `unstable_cache` wrapper but keyed by request URL/body — no tags,
 * no manual invalidation. Editor previews bypass this layer entirely
 * (postMessage updates the inline `<style>` directly); this TTL only
 * controls how stale the *shopper-facing* SSR reads can get after a
 * publish.
 */
const THEME_TTL_SECONDS = 10;

@injectable('EmporixCmsThemeApi', 'Singleton')
class EmporixCmsThemeApi implements IEmporixCmsThemeApi {
  private readonly THEME_ENTITY_TYPE = 'STOREFRONT_CMS_THEME';
  private readonly THEME_MIXIN_KEY = 'CMS_THEME_DATA';

  constructor(
    @inject('EmporixSchemaApi') private schemaApi: EmporixSchemaApi,
    @inject('LoggerService') private logger: LoggerService,
  ) {}

  async getThemeEntity(site: string, version?: 'draft' | 'live' | string): Promise<RawCmsTheme | null> {
    if (!site) return null;
    try {
      const entityId = buildThemeEntityId(site, version);
      let entity = await this.schemaApi.getCustomEntity(this.THEME_ENTITY_TYPE, entityId, THEME_TTL_SECONDS);

      if (!entity) {
        // Fallback: search by mixin attributes. Useful if the editor
        // created the row through bulk import (id generated by Emporix).
        const criteria: Record<string, string> = {
          [`mixins.${this.THEME_MIXIN_KEY}.site`]: site,
        };
        if (version) {
          criteria[`mixins.${this.THEME_MIXIN_KEY}.version`] = version;
        }
        const result = await this.schemaApi.searchCustomEntities(
          this.THEME_ENTITY_TYPE,
          { criteria, size: 1 },
          THEME_TTL_SECONDS,
        );
        entity = result.items?.[0];
      }

      if (!entity) return null;

      const mixin = entity.mixins?.[this.THEME_MIXIN_KEY] as Record<string, unknown> | undefined;
      if (!mixin) return null;

      const variables = this.parseVariables(mixin.variables);
      const { baseId, version: parsedVersion } = parseVersionedId(entity.id ?? buildThemeEntityId(site, version));

      return {
        id: entity.id ?? buildThemeEntityId(site, version),
        site: (typeof mixin.site === 'string' && mixin.site) || site,
        baseTheme: typeof mixin.base_theme === 'string' && mixin.base_theme ? mixin.base_theme : undefined,
        variables,
        version: (typeof mixin.version === 'string' && mixin.version) || parsedVersion,
        baseId: (typeof mixin.base_id === 'string' && mixin.base_id) || baseId,
        author: typeof mixin.author === 'string' ? mixin.author : undefined,
      };
    } catch (error) {
      this.logger.warn(
        { err: error instanceof Error ? error.message : String(error), site, version },
        'Failed to load CMS theme entity — falling back to null',
      );
      return null;
    }
  }

  /**
   * Defensive JSON parsing for the `variables` attribute. Accepts both
   * a JSON string (the normal TEXT-encoded shape) and an already-parsed
   * object (some Emporix deployments expand mixin JSON on read).
   */
  private parseVariables(raw: unknown): Record<string, string> {
    if (raw == null) return {};
    let value: unknown = raw;
    if (typeof value === 'string') {
      const trimmed = value.trim();
      if (!trimmed) return {};
      try {
        value = JSON.parse(trimmed);
      } catch (error) {
        this.logger.warn(
          { err: error instanceof Error ? error.message : String(error) },
          'variables is not valid JSON — ignoring',
        );
        return {};
      }
    }
    if (!value || typeof value !== 'object' || Array.isArray(value)) {
      this.logger.warn({ type: typeof value }, 'variables is not a JSON object — ignoring');
      return {};
    }
    const entries = Object.entries(value as Record<string, unknown>);
    const out: Record<string, string> = {};
    for (const [key, val] of entries) {
      if (typeof val === 'string') out[key] = val;
    }
    return out;
  }
}

export default EmporixCmsThemeApi;
