import dynamic from 'next/dynamic';
import type { CMSComponentEntry } from '@extensions/medienwerft-cms-plugin/types';

const ContactForm = dynamic(() => import('./contact-form-client'));

export const contactFormEntry: CMSComponentEntry = {
  definition: {
    type: 'cms-contact-form',
    label: 'Contact form',
    description:
      'Configurable contact form with subject, email, phone, and description fields. Submissions are stored as FORMSUBMISSIONS custom entities.',
    props: {
      headline: { label: 'Headline', type: 'text' },
      body: { label: 'Intro text', type: 'textarea' },
      show_subject: { label: 'Show subject field', type: 'boolean' },
      show_email: { label: 'Show email field', type: 'boolean' },
      show_phone: { label: 'Show phone field', type: 'boolean' },
      show_description: { label: 'Show description field', type: 'boolean' },
      subject_label: { label: 'Subject label', type: 'text' },
      email_label: { label: 'Email label', type: 'text' },
      phone_label: { label: 'Phone label', type: 'text' },
      description_label: { label: 'Description label', type: 'text' },
      subject_placeholder: { label: 'Subject placeholder', type: 'text' },
      email_placeholder: { label: 'Email placeholder', type: 'text' },
      phone_placeholder: { label: 'Phone placeholder', type: 'text' },
      description_placeholder: { label: 'Description placeholder', type: 'text' },
      submit_label: { label: 'Submit button label', type: 'text' },
      success_message: { label: 'Success message', type: 'text' },
      alignment: {
        label: 'Alignment',
        type: 'select',
        options: [
          { label: 'Left', value: 'left' },
          { label: 'Center', value: 'center' },
          { label: 'Right', value: 'right' },
        ],
      },
      layout: {
        label: 'Layout',
        type: 'select',
        options: [
          { label: 'Stacked', value: 'stacked' },
          { label: 'Two column (email & phone)', value: 'two-column' },
        ],
      },
      max_width: {
        label: 'Max width',
        type: 'select',
        options: [
          { label: 'Narrow', value: 'narrow' },
          { label: 'Content', value: 'content' },
          { label: 'Wide', value: 'wide' },
          { label: 'Full', value: 'full' },
        ],
      },
      density: {
        label: 'Vertical spacing',
        type: 'select',
        options: [
          { label: 'Compact', value: 'compact' },
          { label: 'Comfortable', value: 'comfortable' },
          { label: 'Spacious', value: 'spacious' },
        ],
      },
      tone: {
        label: 'Tone',
        type: 'select',
        options: [
          { label: 'Default', value: 'default' },
          { label: 'Muted', value: 'muted' },
          { label: 'Accent', value: 'accent' },
        ],
      },
    },
    defaultProps: {
      show_subject: true,
      show_email: true,
      show_phone: true,
      show_description: true,
      subject_label: 'Subject',
      email_label: 'Email',
      phone_label: 'Phone',
      description_label: 'Message',
      subject_placeholder: 'What is this regarding?',
      email_placeholder: 'you@example.com',
      phone_placeholder: '+41 …',
      description_placeholder: 'Tell us more about your request…',
      submit_label: 'Send',
      success_message: 'Thank you — we received your message and will get back to you soon.',
      alignment: 'left',
      layout: 'stacked',
      max_width: 'content',
      density: 'comfortable',
      tone: 'default',
    },
  },
  mapProps: (p) => ({
    headline: p.headline,
    body: p.body,
    showSubject: p.show_subject !== false,
    showEmail: p.show_email !== false,
    showPhone: p.show_phone !== false,
    showDescription: p.show_description !== false,
    subjectLabel: p.subject_label,
    emailLabel: p.email_label,
    phoneLabel: p.phone_label,
    descriptionLabel: p.description_label,
    subjectPlaceholder: p.subject_placeholder,
    emailPlaceholder: p.email_placeholder,
    phonePlaceholder: p.phone_placeholder,
    descriptionPlaceholder: p.description_placeholder,
    submitLabel: p.submit_label,
    successMessage: p.success_message,
    alignment: p.alignment,
    layout: p.layout,
    maxWidth: p.max_width,
    density: p.density,
    tone: p.tone,
  }),
  component: ContactForm,
};
